# Generated by Django 5.2.16 on 2026-08-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='img_url',
            new_name='img_urls',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titles',
        ),
    ]
